_:
{
  flake.nixosModules.nixos-hardware-configuration =
    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:

    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "uas"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/mapper/luks-07881c50-229b-470b-8e10-dce17b2961e3";
        fsType = "ext4";
      };

      boot.initrd.luks.devices."luks-07881c50-229b-470b-8e10-dce17b2961e3".device =
        "/dev/disk/by-uuid/07881c50-229b-470b-8e10-dce17b2961e3";

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/C68D-FD5A";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [
        { device = "/dev/mapper/luks-ebb6d9c8-350c-4291-a8bd-74ec17ab4a67"; }
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };

}
