{ inputs, withSystem, ... }:
{
  flake.nixosModules.build-flags-x86-64-v3 =
    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    {
      config,
      lib,
      pkgs,
      ...
    }:
    {
      nixpkgs.hostPlatform = {
        gcc.arch = "x86-64-v3";
        gcc.tune = "x86-64-v3";
        system = "x86_64-linux";
      };
    };

}
