{ inputs, self, ... }:
{
  flake.modules.nixos.hardware-LOQ-15IRX10 =
    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    {
      config,
      lib,
      ...
    }:

    {
      services.xserver.videoDrivers = [ "nvidia" ];

      hardware = {
        facter.reportPath = ./facter.json;
        graphics = {
          enable = true;
          enable32Bit = true;
        };
        nvidia = {
          modesetting.enable = true;
          powerManagement.enable = true;
          powerManagement.finegrained = lib.mkDefault true;
          open = true;
          nvidiaSettings = true;
          # package = config.boot.kernelPackages.nvidiaPackages.latest;
          prime = {
            offload.enable = lib.mkDefault true;
            offload.enableOffloadCmd = lib.mkDefault true;
            sync.enable = lib.mkDefault false;

            intelBusId = "PCI:0:2:0";
            nvidiaBusId = "PCI:1:0:0";
          };
        };
      };

      imports = [
        self.modules.nixos.hardware-lenovo
        inputs.nixos-hardware.nixosModules.common-cpu-intel
        inputs.nixos-hardware.nixosModules.common-gpu-intel
        inputs.nixos-hardware.nixosModules.common-gpu-nvidia
        inputs.nixos-hardware.nixosModules.common-pc-laptop
        inputs.nixos-hardware.nixosModules.common-pc-laptop-ssd
      ];
    };

}
